# Generated by Django 4.2.1 on 2023-08-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='data',
        ),
    ]
